[workspace]
members = ["app", "lib"]
resolver = "3"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
garde = { version = "0.22.0", features = ["derive", "serde"] }
median = "0.3.2"

[profile.dev.package."*"]
opt-level = 2
