[spectrogram]
time_width = 512
image_resolution = 512
max_frequency = 8000.0
min_frequency = 20.0

[fft]
frame_len = 4096
hop_len = 1024
sample_rate = 44100

[hps]
p_filter_span = 10
h_filter_span = 20
p_factor = 2.0
h_factor = 2.0

[light]
width = 20
height = 26
decay = 0.8999999761581421
