[spectrogram]
time_width = 512
image_resolution = 512
max_frequency = 10000.0
min_frequency = 20.0

[fft]
frame_len = 4096
hop_len = 1024
sample_rate = 44100

[hps]
p_filter_span = 8
h_filter_span = 30
p_factor = 3.0
h_factor = 1.2999999523162842

[light]
width = 20
height = 26
decay = 0.8999999761581421
gui_delay = 0

[paint]
roll_len = [12, 5, 3, 2, 2, 1, 1]
roll_opacity = [1.0, 1.0, 0.92, 0.84, 0.76, 0.68, 0.6]
# roll_opacity = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

[loudness]
target_lufs = -10.0
factor = 0.8
